name: CI

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [12.x, 14.x, 15.x, 16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        uses: bahmutov/npm-install@master

      - name: Check Prettier
        run: yarn prettier

      - name: Check Lint
        run: yarn lint

      - name: Build
        run: yarn build
